// src/components/ChallengerQualifierOverlay.jsx
// Visible pre-Major Challenger Qualifier event. Renders a bracket-focused
// layout with clickable match cards (showing real per-map / per-player stats
// generated by the standard CDL match simulation).

import { useState } from "react";
import { useGame } from "../store/gameStore.jsx";
import TeamLogo from "./TeamLogo.jsx";
import SeriesDetail from "./SeriesDetail.jsx";
import { resolveTeamDisplay } from "../utils/teamDisplay.js";
import { useTeamHub } from "../store/teamHubContext.jsx";
import { placementText } from "../utils/placementDisplay.js";

function ratingColor(n) {
  return n >= 80 ? "#86efac" : n >= 74 ? "#bef264" : n >= 68 ? "#fcd34d" : "#fca5a5";
}

function fieldRowToTeam(row) {
  if (!row) return null;
  return { id: row.teamId, name: row.teamName, tag: row.tag, color: row.color, logo: row.logo, region: row.region };
}

function buildFieldMap(rows) {
  return Object.fromEntries((rows || []).map(row => [row.teamId, row]));
}

function scoreFor(match, teamId) {
  if (!match?.played || !match.result) return "";
  if (match.result.teamAId === teamId) return match.result.winsA;
  if (match.result.teamBId === teamId) return match.result.winsB;
  return "";
}

function MatchTeamLine({ row, seed, score, winner, schedule, onTeam, isUser }) {
  if (!row) return <div className="cqo-bm-team empty"><span>TBD</span></div>;
  const display = resolveTeamDisplay(row.teamId, schedule);
  return (
    <div className={`cqo-bm-team ${winner ? "winner" : ""} ${isUser ? "cqo-bm-you" : ""}`}>
      <TeamLogo team={display} size={18} />
      <span className="cqo-bm-seed">#{seed ?? row.seed}</span>
      <span className="cqo-bm-name" onClick={(e) => { e.stopPropagation(); onTeam?.(row.teamId); }}>{display.name ?? row.teamName}</span>
      {isUser && <span className="you-badge">YOU</span>}
      <strong>{score}</strong>
    </div>
  );
}

function BracketMatch({ match, fieldMap, isNext, onClick, schedule, onTeam, userTeamId }) {
  const a = fieldMap[match.a];
  const b = fieldMap[match.b];
  const winnerId = match.result?.winnerId;
  const clickable = !!(a && b);
  const userInvolved = match.a === userTeamId || match.b === userTeamId;
  return (
    <button
      type="button"
      className={`cqo-bm ${match.played ? "played" : ""} ${isNext ? "next" : ""} ${clickable ? "clickable" : ""} ${userInvolved ? "cqo-bm-user" : ""}`}
      onClick={clickable ? onClick : undefined}
      disabled={!clickable}
    >
      <MatchTeamLine row={a} seed={match.seedA} score={scoreFor(match, match.a)} winner={winnerId === match.a} schedule={schedule} onTeam={onTeam} isUser={match.a === userTeamId} />
      <MatchTeamLine row={b} seed={match.seedB} score={scoreFor(match, match.b)} winner={winnerId === match.b} schedule={schedule} onTeam={onTeam} isUser={match.b === userTeamId} />
    </button>
  );
}

function MatchDetailModal({ match, fieldMap, qualifier, schedule, onClose }) {
  if (!match) return null;
  const a = fieldMap[match.a];
  const b = fieldMap[match.b];
  const result = match.result;
  const isPlayed = match.played && result;

  return (
    <div className="cqo-modal-backdrop" onClick={onClose}>
      <div className="cqo-modal" onClick={(e) => e.stopPropagation()}>
        <div className="cqo-modal-header">
          <div>
            <div className="cqo-modal-kicker">{qualifier?.name ?? "Qualifier"} · {match.roundName ?? ""}</div>
            <div className="cqo-modal-title">
              <span>{a?.teamName ?? "TBD"}</span>
              <span className="cqo-modal-vs">vs</span>
              <span>{b?.teamName ?? "TBD"}</span>
            </div>
          </div>
          <button className="cqo-modal-close" onClick={onClose} aria-label="Close">×</button>
        </div>

        {isPlayed ? (
          <div className="cqo-modal-body">
            <div className="cqo-modal-score">
              <div className="cqo-modal-side">
                <TeamLogo team={resolveTeamDisplay(result.teamAId, schedule)} size={28} />
                <strong style={{ color: resolveTeamDisplay(result.teamAId, schedule).color }}>{result.teamAName}</strong>
                <span className="cqo-modal-wins">{result.winsA}</span>
              </div>
              <span className="cqo-modal-final">{result.score}</span>
              <div className="cqo-modal-side">
                <span className="cqo-modal-wins">{result.winsB}</span>
                <strong style={{ color: resolveTeamDisplay(result.teamBId, schedule).color }}>{result.teamBName}</strong>
                <TeamLogo team={resolveTeamDisplay(result.teamBId, schedule)} size={28} />
              </div>
            </div>
            <SeriesDetail result={result} schedule={schedule} />
          </div>
        ) : (
          <MatchPreview a={a} b={b} schedule={schedule} />
        )}
      </div>
    </div>
  );
}

function MatchPreviewSide({ row, schedule }) {
  if (!row) return <div className="cqo-prev-side"><span className="muted">TBD</span></div>;
  const display = resolveTeamDisplay(row.teamId, schedule);
  return (
    <div className="cqo-prev-side">
      <div className="cqo-prev-head">
        <TeamLogo team={display} size={26} />
        <div>
          <strong style={{ color: display.color }}>{row.teamName}</strong>
          <span>{row.region} · OVR {row.teamOvr}</span>
        </div>
      </div>
      <div className="cqo-prev-meta">
        <span>Circuit Pts: <b>{row.circuitPointsBefore ?? 0}</b></span>
        <span>Form: <b>{(row.formBefore ?? 0) > 0 ? "+" : ""}{row.formBefore ?? 0}</b></span>
        <span>Seed: <b>#{row.seed}</b></span>
      </div>
    </div>
  );
}

function MatchPreview({ a, b, schedule }) {
  return (
    <div className="cqo-modal-body">
      <div className="cqo-preview-grid">
        <MatchPreviewSide row={a} schedule={schedule} />
        <span className="cqo-modal-vs cqo-prev-vs">vs</span>
        <MatchPreviewSide row={b} schedule={schedule} />
      </div>
      <p className="cqo-help">Match not yet simulated. Sim it from the controls above to see player stats and map breakdown.</p>
    </div>
  );
}

export default function ChallengerQualifierOverlay() {
  const { state, dispatch } = useGame();
  const { openTeamHub } = useTeamHub();
  const [selectedKey, setSelectedKey] = useState(null);
  const [showField, setShowField] = useState(false);

  if (!state) return null;

  const { schedule } = state;
  if (schedule?.phase !== "challengerQualifier") return null;

  // The Challengers Finals qualifier is opened by Major 4's completion the moment
  // Major 4 finishes. Its completion popup (the Major 4 champion screen) must show
  // FIRST — so while an entered, completed major still has its popup up, yield and
  // let that popup own the screen. Once dismissed (DISMISS_MAJOR clears
  // enteredMajorIdx) this overlay renders the qualifier as normal.
  const pendingIdx = state.enteredMajorIdx ?? null;
  if (pendingIdx != null && schedule.majors?.[pendingIdx]?.completed) return null;

  const qualifier = schedule.currentChallengerQualifier;
  if (!qualifier) return null;

  const isFinals = qualifier.eventType === "challengersFinals";
  const majorIdx = qualifier.majorIdx ?? schedule.majorIdx ?? 0;
  const majorName = isFinals ? "ESWC" : (schedule.majors?.[majorIdx]?.name ?? `Major ${majorIdx + 1}`);
  const eventTitle = qualifier.name || (isFinals ? "Challengers Finals" : "Challenger Qualifier");
  const completed = !!qualifier.completed;
  const fieldRows = qualifier.field || [];
  const fieldMap = buildFieldMap(fieldRows);
  const resultRows = completed ? (qualifier.results || []) : [];
  const qualified = resultRows.filter(r => r.qualified).sort((a, b) => a.placement - b.placement);
  const bracket = qualifier.bracket;

  let nextMatch = null;
  for (const [roundIdx, round] of (bracket?.rounds || []).entries()) {
    const matchIdx = (round.matches || []).findIndex(m => !m.played && m.a && m.b);
    if (matchIdx !== -1) {
      nextMatch = { roundIdx, roundName: round.name, matchIdx, match: round.matches[matchIdx] };
      break;
    }
  }

  const bracketType = bracket?.type ?? "DE16";
  const alive = fieldRows.filter(row => {
    if (completed) return false;
    const losses = (qualifier.matchLog || []).filter(m => m.loserId === row.teamId).length;
    return losses < 2;
  });

  const matchByKey = (key) => {
    if (!key) return null;
    const [r, m] = key.split(":").map(Number);
    const round = bracket?.rounds?.[r];
    const mtch = round?.matches?.[m];
    if (!mtch) return null;
    return { ...mtch, roundName: round.name };
  };

  return (
    <div className="cqo-backdrop">
      <div className="cqo-card cqo-card-wide">
        <div className="cqo-header">
          <div>
            <div className="cqo-kicker">CHALLENGERS EVENT</div>
            <h1>{eventTitle}</h1>
            <p>Season {schedule.season} · {isFinals ? "Top Challengers feed ESWC" : `${majorName} Qualifier`} · {fieldRows.length}-team {bracketType === "DE24" ? "double elimination with seeds 1–8 byes" : "double elimination"} · {isFinals ? "Top 4 qualify for ESWC" : "Top 4 qualify (Major seeds 13–16)"}</p>
          </div>
          <div className={`cqo-status ${completed ? "complete" : "pending"}`}>
            {completed ? "Complete" : nextMatch ? nextMatch.roundName : "Ready"}
          </div>
        </div>

        <section className="cqo-control-strip">
          <div>
            <span className="cqo-label">Next Match</span>
            <strong>{nextMatch ? `${fieldMap[nextMatch.match.a]?.teamName || "TBD"} vs ${fieldMap[nextMatch.match.b]?.teamName || "TBD"}` : completed ? "Qualifier complete" : "Building bracket"}</strong>
          </div>
          <div>
            <span className="cqo-label">Teams Alive</span>
            <strong>{completed ? 1 : alive.length}</strong>
          </div>
          <div>
            <span className="cqo-label">Locked Qualified</span>
            <strong>{qualified.length ? qualified.map(r => r.tag || r.teamName).join(", ") : "Top 4 pending"}</strong>
          </div>
          <div className="cqo-cs-actions">
            {!completed ? (
              <>
                {state.userTeamType === "challenger" && fieldRows.some(r => r.teamId === state.userTeamId) && (
                  <button className="btn-cta" onClick={() => dispatch({ type: "SIM_USER_CHALLENGER_QUALIFIER_MATCH" })}>Play Your Match</button>
                )}
                <button className="btn-secondary" onClick={() => dispatch({ type: "SIM_NEXT_CHALLENGER_QUALIFIER_MATCH" })}>Sim Next Match</button>
                <button className="btn-secondary" onClick={() => dispatch({ type: "SIM_CHALLENGER_QUALIFIER_ROUND" })}>Sim Round</button>
                <button className="btn-cta" onClick={() => dispatch({ type: "SIM_CHALLENGER_QUALIFIER" })}>Finish Qualifier</button>
              </>
            ) : (
              <button className="btn-cta" onClick={() => dispatch({ type: "CONTINUE_FROM_CHALLENGER_QUALIFIER" })}>
                Continue to {isFinals ? "CDL Champs" : majorName} →
              </button>
            )}
          </div>
        </section>

        <section className="cqo-bracket-section">
          <div className="cqo-section-head">
            <div className="cqo-panel-title">Bracket</div>
            <button className="cqo-toggle" onClick={() => setShowField(s => !s)}>
              {showField ? "Hide Field ▴" : "Show Field ▾"}
            </button>
          </div>

          {showField && (
            <div className="cqo-field-strip">
              {fieldRows.map(row => (
                <div key={row.teamId} className="cqo-field-chip">
                  <span className="cqo-seed">#{row.seed}</span>
                  <TeamLogo team={fieldRowToTeam(row)} size={18} />
                  <button className="link-button team-link cqo-field-name" onClick={() => openTeamHub(row.teamId)}>{row.teamName}</button>
                  <span className="cqo-field-region">{row.region}</span>
                  <span style={{ color: ratingColor(row.teamOvr), fontWeight: 900 }}>{row.teamOvr}</span>
                </div>
              ))}
            </div>
          )}

          <div className="cqo-bracket-scroller">
            {(bracket?.rounds || []).map((round, roundIdx) => (
              <div key={round.name} className={`cqo-bracket-round ${round.type?.toLowerCase() || ""}`}>
                <h4>{round.name}</h4>
                {round.matches?.length ? round.matches.map((match, matchIdx) => (
                  <BracketMatch
                    key={`${round.name}_${matchIdx}`}
                    match={match}
                    fieldMap={fieldMap}
                    isNext={nextMatch?.roundIdx === roundIdx && nextMatch?.matchIdx === matchIdx}
                    onClick={() => setSelectedKey(`${roundIdx}:${matchIdx}`)}
                    schedule={schedule}
                    userTeamId={state.userTeamId}
                  />
                )) : <div className="cqo-round-empty">Awaiting results</div>}
              </div>
            ))}
          </div>
        </section>

        {completed && (
          <section className="cqo-qualified-card">
            <div className="cqo-panel-title">Final Placements</div>
            <div className="cqo-table cqo-results-table">
              <div className="cqo-row cqo-row-head">
                <span>Place</span><span>Team</span><span>OVR</span><span>Record</span><span>Pts</span><span>Status</span>
              </div>
              {resultRows.map(row => (
                <div key={row.teamId} className={`cqo-row ${row.qualified ? "qualified" : row.placement <= 8 ? "near" : "missed"}`}>
                  <span className="cqo-seed">{placementText(row.placement)}</span>
                  <span className="cqo-team">
                    <TeamLogo team={fieldRowToTeam(row)} size={22} />
                    <span>{row.teamName}</span>
                  </span>
                  <span style={{ color: ratingColor(row.teamOvr), fontWeight: 800 }}>{row.teamOvr}</span>
                  <span>{row.bracketResult || row.performanceScore || "—"}</span>
                  <span>+{row.circuitPointsAwarded}</span>
                  <span className={row.qualified ? "cqo-qualified-pill" : "cqo-missed-pill"}>
                    {row.qualified ? "Qualified" : "Missed"}
                  </span>
                </div>
              ))}
            </div>
          </section>
        )}

        {completed && qualified.length === 4 && (
          <section className="cqo-qualified-card">
            <div className="cqo-panel-title">Major Seeds 13–16</div>
            <div className="cqo-qualified-grid">
              {qualified.map((row, idx) => (
                <div key={`q_${row.teamId}`} className="cqo-qualified-team">
                  <span className="cqo-seed-large">{idx + 13}</span>
                  <TeamLogo team={fieldRowToTeam(row)} size={28} />
                  <div>
                    <strong>{row.teamName}</strong>
                    <span>{row.placementLabel} · OVR {row.teamOvr}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}
      </div>

      {selectedKey && (
        <MatchDetailModal
          match={matchByKey(selectedKey)}
          fieldMap={fieldMap}
          qualifier={qualifier}
          schedule={schedule}
          onClose={() => setSelectedKey(null)}
        />
      )}
    </div>
  );
}
