import assert from "node:assert/strict";
import { buildInitialRoster } from "../src/data/players.js";
import { buildSeason } from "../src/engine/seasonEngine.js";
import { createHistoricalCareer } from "../src/engine/historicalDynasty.js";
import { buildBoardObjectives, migrateBoardState } from "../src/engine/boardEngine.js";
import { migrateModernCdlCareer, getModernCdlTeamExpectation, generateModernCdlEventExpectation, evaluateModernCdlEventPerformance, evaluateManagerJobStatus, dismissModernCdlManager, generateModernCdlJobInterest, acceptModernCdlJobOffer } from "../src/engine/modernCdlCareer.js";

let count=0; const check=(ok,msg)=>{assert.ok(ok,msg);console.log(`✓ ${++count}. ${msg}`)};
const players=buildInitialRoster(); let state={userTeamId:"optic",userTeamType:"cdl",careerMode:"modern",season:1,players,schedule:buildSeason(1),boardState:migrateBoardState(null),seasonHistory:[]};
const built=buildBoardObjectives(state); state.boardState={...state.boardState,...built}; state=migrateModernCdlCareer(state);
check(state.schedule.stages.length===4,"Modern CDL starts"); check(!!state.managerCareer,"manager profile created"); check(state.managerCareer.reputation>=0&&state.managerCareer.reputation<=100,"starting reputation valid"); check(state.managerCareer.jobSecurity>=60&&state.managerCareer.jobSecurity<=75,"starting job security valid");
check(state.managerCareer.currentObjectives.length===3,"readable objectives generated"); const elite=getModernCdlTeamExpectation(state,state.userTeamId); const weakest=[...new Set(players.map(p=>p.teamId).filter(Boolean))].map(id=>getModernCdlTeamExpectation(state,id)).sort((a,b)=>b.powerRank-a.powerRank)[0]; check(elite.targetMajorPlacement<weakest.targetMajorPlacement,"objectives/expectations reflect team strength");
check(state.managerCareer.currentObjectives.every(o=>o.deadlineEventId),"objectives have possible deadlines"); const expectation=generateModernCdlEventExpectation(state,0); check(!!expectation&&expectation.expectedPlacement,"event expectation generated");
function completeAt(s,place){const foes=[...new Set(players.map(p=>p.teamId).filter(Boolean))].filter(id=>id!==s.userTeamId);let rounds;if(place===1)rounds=[{type:"GF",name:"Grand Final",matches:[{played:true,result:{winnerId:s.userTeamId,loserId:foes[0]}}]}];else if(place===2)rounds=[{type:"GF",name:"Grand Final",matches:[{played:true,result:{winnerId:foes[0],loserId:s.userTeamId}}]}];else rounds=[{name:"LB Round 3",matches:[{played:true,result:{winnerId:foes[0],loserId:s.userTeamId}}]},{type:"GF",name:"Grand Final",matches:[{played:true,result:{winnerId:foes[1],loserId:foes[2]}}]}];const majors=s.schedule.majors.map((m,i)=>i===0?{...m,completed:true,bracket:{rounds,champion:foes[1]}}:m);return {...s,schedule:{...s.schedule,majors}}}
let over=evaluateModernCdlEventPerformance(completeAt(state,1),0); check(over.managerCareer.eventReviews.length===1,"Major result evaluated"); check(over.managerCareer.jobSecurity>state.managerCareer.jobSecurity,"overperformance raises confidence");
let underBase={...state,managerCareer:{...state.managerCareer,currentEventExpectation:{...expectation,expectedPlacement:2,minimumAcceptable:4}}};let under=evaluateModernCdlEventPerformance(completeAt(underBase,8),0);check(under.managerCareer.jobSecurity<state.managerCareer.jobSecurity,"underperformance lowers confidence");
let again=evaluateModernCdlEventPerformance(over,0);check(again.managerCareer.reputation===over.managerCareer.reputation,"reputation applies once");check(again.managerCareer.jobSecurity===over.managerCareer.jobSecurity,"security applies once");check(!!over.pendingCareerBoardReview,"board reaction created");check(over.managerCareer.completedObjectives.length>=0,"objective completion path safe");check(under.managerCareer.currentObjectives.every(o=>["active","completed","failed","expired"].includes(o.status)),"objective failure/status path safe");
let warn=evaluateManagerJobStatus({...state.managerCareer,jobSecurity:45});check(warn.warningLevel==="concern","board concern issued");warn=evaluateManagerJobStatus({...warn,jobSecurity:30});check(warn.warningLevel==="formal","formal warning issued");warn=evaluateManagerJobStatus({...warn,jobSecurity:15});check(warn.warningLevel==="final"&&!!warn.activeUltimatum,"final ultimatum issued");let sacked=evaluateManagerJobStatus({...warn,jobSecurity:10,consecutiveUnderperformances:3});check(sacked.employmentStatus==="unemployed","manager can be sacked");
let dismissed=dismissModernCdlManager({...state,managerCareer:{...warn,employmentStatus:"employed"}},"Diagnostic dismissal");check(dismissed.managerCareer.employmentStatus==="unemployed","sacked manager unemployed");check(dismissed.schedule===state.schedule&&dismissed.players===state.players,"sacking preserves world");
let market=generateModernCdlJobInterest({...state,managerCareer:{...state.managerCareer,reputation:90,employmentStatus:"unemployed"}},{force:true});check(market.managerCareer.jobOffers.length>0,"job offer generated");const offer=market.managerCareer.jobOffers[0];const snapshots={schedule:market.schedule,players:market.players,standings:market.schedule.standings,results:market.schedule.matchLog};let switched=acceptModernCdlJobOffer(market,offer.id);check(switched.userTeamId===offer.teamId,"acceptance changes controlled team");check(switched.schedule===snapshots.schedule&&switched.players===snapshots.players&&switched.schedule.standings===snapshots.standings&&switched.schedule.matchLog===snapshots.results,"switch preserves calendar standings rosters results");check(switched.managerCareer.careerHistory.length===2,"career history records move");
const ach=over.managerCareer.achievements.length;again=evaluateModernCdlEventPerformance(over,0);check(again.managerCareer.achievements.length===ach,"achievements unlock once");const reload=migrateModernCdlCareer(JSON.parse(JSON.stringify(switched)));check(JSON.stringify(reload.managerCareer)===JSON.stringify(switched.managerCareer),"save/reload preserves career data");const legacy=migrateModernCdlCareer({...state,managerCareer:undefined});check(!!legacy.managerCareer&&legacy.userTeamId===state.userTeamId&&legacy.schedule===state.schedule,"existing Modern save migrates safely");const hist=createHistoricalCareer("ghosts",{userTeamId:"optic-gaming"});check(!!hist,"Historical Dynasty starts");const histState={...hist,userTeamType:"historical",careerMode:"historical"};check(migrateModernCdlCareer(histState)===histState,"Historical Dynasty data not modified");
console.log(`\nPASS: ${count} Modern CDL career checks (all 30 required areas covered).`);
